FROM node:18.20.3 as base

# Install pnpm globally
RUN npm install -g pnpm

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json .

RUN pnpm install

COPY . /usr/src/app

CMD [ "pnpm", "run", "dev"]